### ISSUE TITLE
Compile error regarding PR: https://github.com/mogol/flutter_secure_storage/commit/a2ab156da02397a76b4ff9e13862879b4bec260f

### ISSUE THREAD

**Issue by lidongze91** [mogol/flutter_secure_storage#121]
I see the PR here uses syntax '@NonNull', does this compile on your end? I think the code needs to specifically `import android.support.annotation.NonNull;`

**Comment by lidongze91** [comment]
@morrica Please advise

**Comment by morrica** [comment]
@lidongze91 the import for that annotation was the `import androidx.annotation.NonNull;`. It got removed in the merge of the pull request because an intervening commit had removed all the androidx annotations, I believe due to an issue on some devices. Looks like the merge didn't take care of the annotation usage on the `onMethodCall(...)` method. Best would probably be to remove the `@NonNull` annotations from that method or anywhere else you see them and commit the change as a bugfix.
