### ISSUE TITLE
Instance of 'Mo'

### ISSUE THREAD

**Issue by TMSantos** [mogol/flutter_secure_storage#221]
Hey, I'm not sure if this is related to flutter secure storage, but putting it here to seek opinions, if no one says anything I'll close anyway.

I'm getting weird error logs from production with the error :
`Instance of 'Mo'`

Looking into the stacktrace, the line this happens is when fluttersecurestorage performs a read call or write call. 

Any clue of what this might be?

Platform: iOS
Mode: release version and obfuscated

**Comment by jakobleck** [comment]
Same here, more or less: Getting an `Instance of 'Co'` in logs from production. Also
Platform: iOS
Mode: release version and obfuscated

This happens when a read is attempted. I have no definitive further info on what it is, deobfuscation did not work, but it came up while trying to debug problems that appeared on some users' devices with access to the keychain, possibly related to stuff like https://developer.apple.com/forums/thread/26168. And in similar test code executed at the same time where I get an error message (which, of course, does not have to be the same problem), it shows an OSStatus -25308. Weirdly, `UIApplication.shared.isProtectedDataAvailable` (accessed via a PlatformChannel) in several instances returns true before the above happens.
