### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by e-oheredia** [mogol/flutter_secure_storage#236]
Hi everyone, 

Don't know what is really the problem with my code, 

`void main() async {
  //await GlobalConfiguration().loadFromAsset("config");
  final FlutterSecureStorage secureStorage = const FlutterSecureStorage();
  bool contieneAccessToken =
      await secureStorage.containsKey(key: 'access_token');
  Widget defaultHome = HomePage();
  if (contieneAccessToken) {
    String? accessToken = await secureStorage.read(key: 'access_token');
    if (accessToken == null) {
      defaultHome = LoginPage();
    }
  }

  runApp(MyApp(defaultHome));
}`

There is an exception: 

`E/flutter ( 7031): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7031): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 7031): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 7031): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 7031): #3      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50:42)
E/flutter ( 7031): #4      FlutterSecureStorage.containsKey (package:flutter_secure_storage/flutter_secure_storage.dart:71:15)
E/flutter ( 7031): #5      main (package:cargo_app/main.dart:11:27)
E/flutter ( 7031): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 7031): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 7031): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 7031): #9      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 7031): #10     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 7031): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 7031): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 7031): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 7031):`

Please help me with this, thank you

**Comment by vadim-rm** [comment]
I have the same problem. Did you manage to solve it?

**Comment by vadim-rm** [comment]
After tests I noticed that the values are not saved after restarting the application

**Comment by vadim-rm** [comment]
I ran some tests and realized that the read function does not work in `void main()`. Reading encrypted parameters works after starting the application itself and rendering the first frame. This looks very strange, since the ability to track the state of the user's login by the presence of tokens is lost, as well as to initialize the Api class before starting the application.

**Comment by vadim-rm** [comment]
Same as #219

**Comment by fabianignacio** [comment]
same issue

fixed with `WidgetsFlutterBinding.ensureInitialized();` on `void main()` and `<application ... android:allowBackup="false" android:fullBackupContent="false">` on `AndroidManifest.xml` to avoid `Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT` on production APK
