### ISSUE TITLE
How to test without running the Material app?

### ISSUE THREAD

**Issue by slamethendry** [mogol/flutter_secure_storage#29]
I could not locate the test file in the repo.  I understand that flutter is a dependency.  

Is it possible to create tests without creating and running the Material UI app.  If yes, is there any sample code that you can share, please?

Thank you.

**Comment by mogol** [comment]
Thanks for the question. 

The plugin could be run only on devices/simulators/emulators, because it contains platform specific logic (keychain in iOS , key store in android). 

I could recommend to create your own wrapper and 
* pass it into your widgets via dependency injection 
* use approach to get parent widget like  https://docs.flutter.io/flutter/widgets/BuildContext/inheritFromWidgetOfExactType.html

Then you would be able to use mock implementation and run without real app.

**Comment by slamethendry** [comment]
I see.  Thank you.

**Comment by hjJunior** [comment]
Could you provide an example?
When I'm run any test that invokes Flutter Secure Storage I got this error
````
  MissingPluginException(No implementation found for method write on channel plugins.it_nomads.com/flutter_secure_storage)
  package:flutter/src/services/platform_channel.dart 291:7          MethodChannel.invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                        _AsyncAwaitCompleter.completeError
  package:flutter/src/services/platform_channel.dart                MethodChannel.invokeMethod
  ===== asynchronous gap ===========================
  dart:async                                                        _asyncThenWrapperHelper
  package:flutter/src/services/platform_channel.dart                MethodChannel.invokeMethod
  package:flutter_secure_storage/flutter_secure_storage.dart 12:12  FlutterSecureStorage.write
````

I just have a class that save and get, and I'm testing:

````
void main() {
  UserSettings userSettings = UserSettings();

  test('it saves user token', () async {
    await userSettings.setUserToken("random_token");
    final String value = await userSettings.getUserToken;
    expect(value, "random_token");
  });
}
````
