### ISSUE TITLE
Feature request: add shared KeyStore/KeyChain possibility

### ISSUE THREAD

**Issue by pdefuns** [mogol/flutter_secure_storage#31]
It would be really nice to have the possibility of sharing KeyChain/KeyStore between two or multiple apps. Is there any plan about this?

**Articles:**
- [Android: sharedUserId](https://stackoverflow.com/questions/11025234/how-can-i-share-a-sharedpreferences-file-across-two-different-android-apps)
- [iOS: Shared Keychain (Keychain Groups)](https://evgenii.com/blog/sharing-keychain-in-ios/)

**Comment by Maleandr** [comment]
Hi working on PR to address keychain sharing on iOS. We use it for our extensions.

**Comment by fuyanzhi1234** [comment]
I have the same request, thanks

**Comment by andreadelfante** [comment]
Hi, any news about this useful feature request?

**Comment by PapyElGringo** [comment]
Hey guys I need to access to Keychain from a `Notification Service Extension` in order to decrypt Encrypted notifications and the key to do that is stored in the Keychain.

I'm trying to use the keychain sharing capabilities from the iOS App but I failed to do it since there is this issue is it event possible?

**Comment by SYND-GITHUB** [comment]
Dear @juliansteenbakker 
How about this feature?
If it is integrated, so could you please show a guideline?
Thanks so much!

**Comment by juliansteenbakker** [comment]
Fixes in 6.1.0-beta.1
