### ISSUE TITLE
EncryptedSharedPreferences initialization failed

### ISSUE THREAD

**Issue by Zrufy** [mogol/flutter_secure_storage#414]
hi all today i am having this problem with my flutter application. But this problem only exists when I upload the bundle to the play store. If I try through android studio I can't recreate this error. I'm using 5.0.2. Has anyone encountered the same error?

**Comment by deveusopht** [comment]
Hello,
Yes I am having the same issue. Using 5.0.2, the issue does not occur on debug apk, however it is appearing in release apk or if I use the command flutter run --release

**Comment by micheleselea** [comment]
I think I bump into the same issue, I had to use this option
```
AndroidOptions _getAndroidOptions() =>
      const AndroidOptions(
        encryptedSharedPreferences: false,
      );
```
because with true the application did not start and I get the EncryptedSharedPreferences initialization from log cat, but only when I put the bundle for releasing on play store, otherwise using directly the apk to install on devide I have no problem.
It seems like google make some kind of optimization that broke the inizialization of encryptedSharedPreferences or something like that

**Comment by micheleselea** [comment]
@deveusopht I think for me did not happen in apk release, but I'll make a try

**Comment by micheleselea** [comment]
@deveusopht I can confirm you I have no problem with apk release or run --release but only with app bundle on playstore

**Comment by Zrufy** [comment]
same!I can't even figure out how to solve this problem

**Comment by Zrufy** [comment]
beyond the solutions written before no solution.

**Comment by juliansteenbakker** [comment]
Version 5.1.0 is out which refactors the android code. Please try again and if the issue still exists feel free to comment or create a new issue.

**Comment by acoutts** [comment]
We are still having the issue @juliansteenbakker in the latest release

**Comment by micheleselea** [comment]
I think I'm using now and I don't have the problem I had before
