### ISSUE TITLE
Major version bump for Android SDK upgrades

### ISSUE THREAD

**Issue by swch01** [mogol/flutter_secure_storage#431]
You bumped the minor version (from `5.0.2` to `5.1.0`) when you upgraded to Android SDK 33. My project picked up that change automatically when I ran `flutter pub upgrade`. Because my project is not using Android SDK 33 yet, I got a build warning and had to pin my version of `flutter_secure_storage` to `5.0.2` in `pubspec.yaml`. Because SDK upgrades cause build warnings and potentially runtime bugs, you could save your users some trouble by bumping your major version along with those upgrades.

**Comment by Kolhammer1** [comment]
Plus one, and it's causing major issues with gradle for me and my collegues.

**Comment by juliansteenbakker** [comment]
I'm sorry for all the trouble this caused. What i'm gonna do is publish a new version 5.1.1 which reverts the braking changes, and publish 6.0.0 with them.

**Comment by Kolhammer1** [comment]
I feel the only real issue is that currently android gradle build tools is only at 7.2.0 which has only been updated and confirmed to work with SDK 32 and 33 is counted as unstable until the gradle build tools catch up. I could be wrong in this but that was the highest I could find and able to get working.

**Comment by juliansteenbakker** [comment]
It's quite strange because on my computer i got a warning that i should use the latest targetSdkVersion which was SDK 33. However on a computer of my colleague that message is not being displayed.

You are right about the gradle part. I did not however find any issues during testing on my local devices with this gradle version and SDK 33.

Still, i think its best to just revert to 32 in a minor upgrade, so commands like `flutter pub upgrade` don't upgrade to a version with breaking changes.

**Comment by juliansteenbakker** [comment]
I have published version 5.1.2 which runs on sdk 32, and 6.0.0 which runs on sdk 33. I hope this will solve the issue.
