### ISSUE TITLE
gnome-keyring requirement for Linux not mentioned in README

### ISSUE THREAD

**Issue by inexcode** [mogol/flutter_secure_storage#463]
Hi! 

For a long time we couldn't launch our app on Arch Linux because we didn't know that `gnome-keyring` is required for the `libsecret` to work.

Only with the latest release we got the proper error log, and I think that this requirement should be mentioned in "Configure Linux Version" section of README to avoid other's frustration.

**Comment by spinus** [comment]
`gnome-keyring` is not required at all. What is required is application that runs as secret service (provides dbus interface for that). I'm running mine with keepassxc and works quite fine.

In other words:
- you need dbus session (also mentioned in #464)
- secret store provider app (gnome-keyring, kde waller, keeassxc, pass-secret-store or other)

**Comment by spinus** [comment]
I may revisit statement above as someone mentioned that might be required as libsecret before certain version uses gnome-keyring protocol instead of new generic secret protocol. I was checking gnome-keyring-daemon 0.42.1 and that seem not work well together.  

Seems like only specific combination of libsecret and gnome-keyring would work.

**Comment by spinus** [comment]
@inexcode can you tell with what versions you found working combination?

**Comment by inexcode** [comment]
> @inexcode can you tell with what versions you found working combination?

Not sure now, all I can tell is that we used libsecret 0.20.5 in our flatpak builds.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
