### ISSUE TITLE
v7.0.0 Upgraded from v6.0.0 is not working [Tested on Android Device Only]

### ISSUE THREAD

**Issue by bamakant** [mogol/flutter_secure_storage#487]
While reading the data from Flutter Secure Storage getting the below exception.

```
I/flutter (31903): PlatformException(Exception encountered, read, java.lang.ArrayIndexOutOfBoundsException: src.length=6 srcPos=0 dst.length=16 dstPos=0 length=16
I/flutter (31903): 	at java.lang.System.arraycopy(Native Method)
I/flutter (31903): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:84)
I/flutter (31903): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.decodeRawValue(FlutterSecureStorage.java:243)
I/flutter (31903): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.read(FlutterSecureStorage.java:65)
I/flutter (31903): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:156)
I/flutter (31903): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (31903): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (31903): 	at android.os.Looper.loopOnce(Looper.java:201)
I/flutter (31903): 	at android.os.Looper.loop(Looper.java:288)
I/flutter (31903): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (31903): , null)
```

FYI: Tested on Android only

I can't see any specific changes need to do after upgrading to v.7.0.0. 

Please let me know if I am missing any specific changes to make.

**Comment by adil192** [comment]
Just to add to this, it's working on Linux but not Android for me

**Comment by bamakant** [comment]
@juliansteenbakker I am using` encryptedSharedPreferences: true `and also passing this to `read()`. It was working fine till v6.1.0

**Comment by juliansteenbakker** [comment]
and are you passing this to all the other functions aswell, like 'readall()`, 'write()`,  'containsKey() or `delete()`?

**Comment by adil192** [comment]
I wasn't using any `aOptions`: [code snippet](https://github.com/adil192/saber/commit/a091270709686c0b5a217fa9ecb71dc890835222#diff-2be368a7ccb5f92f1718372c2763175fb1ea8e81f5092c507a4036e7d9993ac5L251)
```dart
  // simplified

  @override
  Future<T?> _load() async {
    _storage ??= const FlutterSecureStorage();

    String value = await _storage!.read(key: key);
    ...
  }

  @override
  Future _save() async {
    _storage ??= const FlutterSecureStorage();

    return await _storage!.write(key: key, value: value as String);
  }
```

**Comment by juliansteenbakker** [comment]
So the problem here is that a value gets saved with the `EncryptedSharedPreferences` library, but gets read without the 'encryptedSharedPreferences` parameter. This will cause the plugin to think additional decrypting is needed, while it is already decrypted. Hence why the decryption process failes.

With version 6.0.0 and lower, the internal SharedPreference object was reloaded everytime a call was done (like read() or write()). This is why mixed usage of the options parameter worked fine. HOWEVER, this changed with version 7.0.0 because this kind of mixed usage can cause unwanted behaviour when using functions like containsKey(), which can only check SharedPreference OR SecureSharedPerference but not both at the same time.

This change however breaks the usage of mixed options usage. Which is why
a. I need to let the internal sharedPreference object refresh everytime, but keep problems with containsKey()
b. OR: remove the options parameter from every single function, and only allow passing it to the constructor.

@adil192 In your case the keys and values already exists in the SecureSharedPreference object because you are using another plugin. However, FlutterSecureStorage() doesn't know this so it still tries to decode it, even when it's decoded already and so it throws the error.

**Comment by bamakant** [comment]
@juliansteenbakker Thanks for your quick support. I am not facing the issue with v7.0.1 anymore.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.

**Comment by Mangoo0110** [comment]
Hello there,

It looks like this issue has been reported before. I'd like to know if it has been resolved since then, because I am currently facing a similar problem with my application, which is now in testing on the Play Console.

The app gets stuck on the splash screen. I enabled log output using:
`adb logcat | grep Flutter`

And I consistently see the following logs:
```
11-27 17:03:29.709 30141 30141 E flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.decodeRawValue(FlutterSecureStorage.java:262)
11-27 17:03:29.709 30141 30141 E flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.read(FlutterSecureStorage.java:79)
11-27 17:03:29.709 30141 30141 E flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:148)
11-27 17:03:31.424 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.decodeRawValue(FlutterSecureStorage.java:262)
11-27 17:03:31.424 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.read(FlutterSecureStorage.java:79)
11-27 17:03:31.424 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:148)
11-27 17:03:31.606 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.decodeRawValue(FlutterSecureStorage.java:262)
11-27 17:03:31.606 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.read(FlutterSecureStorage.java:79)
11-27 17:03:31.606 30141 30141 I flutter :      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:148)
```

Interestingly, if I clear all app data from the Android system settings, the app starts working normally again — which suggests that something stored by FlutterSecureStorage is causing a failure when the app attempts to read it.

In my case, I was not using or passing aOptions or iOptions to the FlutterSecureStorage() constructor.

Any guidance would be appreciated. Thank you.
