### ISSUE TITLE
[iOS] When you delete an app, the data is also deleted. It cannot be read back.

### ISSUE THREAD

**Issue by ttb-inc** [mogol/flutter_secure_storage#547]
Hi

I'm using "flutter_secure_storage 8.0.0".

I used to be able to get my data back after deleting the app, but now it doesn't seem to work.
Is this a bug? Or is there an option? I'd like to know.

Thanks.

**Comment by Mino5531** [comment]
Hi,
the survival of iOS keychain values is undocumented behavior and should not be relied on. 
There is no option to force this kind of behavior since apple themselves have said that they can't give any reassurances regarding this behavior. Read more about this [here](https://developer.apple.com/forums/thread/36442) and [here](https://developer.apple.com/forums/thread/22874?answerId=75464022#75464022)
Apple probably removed this behavior in one of the latest updates.

Hope this helps.

**Comment by ttb-inc** [comment]
> 

I'll check it out.
Thank you.
