### ISSUE TITLE
[Question] Synchronization between devices

### ISSUE THREAD

**Issue by mjwhodur** [mogol/flutter_secure_storage#553]
Hello everyone,

I have a question, maybe stupid. Just started developing apps in Flutter. So I have a question. I don't know all the implementation quirks and differences between various frameworks and platforms.

My question is: I want to store a value that should be backed up (encryption key) in secure storage. Will the secure storage synchronize between devices? I.e. between iOS -> iOS or Android -> Android. Namely, the user buys a new phone, and will the recovery from backup from cloud services restore the parameters stored in secure storage?

**Comment by kev-techi** [comment]
Hey, on iOS keychain does this out of the box if it's enabled (and it's enabled by default). It will backup and synchronize to devices signed in to the same iCloud account. It works even for macOS <-> iOS.

On Android, it's a different story. It will backup but the backup will only be usable by the same device from which the backup was generated. This is with encryption enabled. This is due to the device using it's own local key to encrypt the data and that local keystore not being backed up. ([read more here](https://thecodeside.medium.com/android-auto-backup-keystore-encryption-broken-heart-love-story-8277c8b10505)) [potential solution here](https://stackoverflow.com/a/61770160/7012894)

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
