### ISSUE TITLE
[Question] For web, how is the unique encryption key generated and securely reused?

### ISSUE THREAD

**Issue by timmolter** [mogol/flutter_secure_storage#579]
Looking at this file: https://github.com/mogol/flutter_secure_storage/blob/develop/flutter_secure_storage_web/lib/flutter_secure_storage_web.dart#L93,

it looks like a random key is generated and stored, but how is that raw key protected?

**Comment by tim-eucalyptus** [comment]
For example what would prevent a hacker or virus software from reading the browser's localStorage file/database? AFAIK localStorage is not encrypted itself by the operating system or otherwise.

Here: https://github.com/mogol/flutter_secure_storage/blob/bdd191faa0ac5e53470e0dd0409849d9ff310a95/flutter_secure_storage_web/lib/flutter_secure_storage_web.dart#L115C29-L115C29

, we see that the encryption key is stored right next to the data stored in localStorage.

**Comment by janosgy** [comment]
Is it really the case? Then what's the point of encrypting data if the encryption key is stored in the same location?

**Comment by polanfong** [comment]
Keen to hear what can be done here as @janosgy has stated above.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
