### ISSUE TITLE
Message: The specified item already exists in the keychain, IOS 

### ISSUE THREAD

**Issue by yourior** [mogol/flutter_secure_storage#711]
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 
> PlatformException(Unexpected security result code, Code: -25299, Message: The specified item already exists in the keychain., -25299, null)
> #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
> #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
> <asynchronous suspension>
> #2      WriteStringStorage (package:pkgname/Storage/Secure_Storage.dart:34:10)
> <asynchronous suspension>
> #3      GoRouterSplashScreen.build.<anonymous closure>.<anonymous closure> (package:pkgname/Splash_Screen.dart:39:13)
> <asynchronous suspension>
> #4      GoRouterSplashScreen.build.<anonymous closure> (package:pkgname/Splash_Screen.dart:36:9)
> <asynchronous suspension>
> #5      _FlutterSplashScreenState.didChangeDependencies (package:another_flutter_splash_screen/another_flutter_splash_screen.dart:325:7)
> <asynchronous suspension>
> Type: Notice | Timestamp: 2024-05-11 09:26:17.155593+07:00 | Process: Runner | Library: Flutter | TID: 0x12e46f

here is my initialize code 
```
AndroidOptions _getAndroidOptions() => const AndroidOptions(
  encryptedSharedPreferences: true,
);

IOSOptions _getIOSOptions() => const IOSOptions(
  // synchronizable: true,
  accessibility: KeychainAccessibility.first_unlock
);
final storage = FlutterSecureStorage(
  aOptions: _getAndroidOptions(),
  iOptions: _getIOSOptions()
);
```
the error showed when i want to write a value into a key

`storage.write(key: Keyname,value: value);`

>  version: "9.1.1"

is this a bug or is there a setting that i need to set for IOS? because this works in android

**Comment by KasperTidemann** [comment]
@yourior I’m seeing the same error here, not sure what it’s related to just yet. It used to work just fine, so I’m currently investigating.

**Comment by yourior** [comment]
@KasperTidemann it works by initializing it using the default method
`final storage = const FlutterSecureStorage();`
then call the option using the function
`storage.write(key: Keyname,value: value,iOptions: _getIOSOptions(),aOptions: _getAndroidOptions());`

**Comment by viphoamt** [comment]
I also had the same error. Please help me!

**Comment by Thioby** [comment]
This is beacuse of that changes:
https://github.com/mogol/flutter_secure_storage/commit/1364ad9937bcd7834142aff967fc40d288ea8ea8

**Comment by devapalanisamy** [comment]
use `readAll` to get value from Storage. `(await secureStorage.readAll())[StorageConstants.secureStorageKey];` This fixes the issue

**Comment by PROGrand** [comment]
None of previous suggestion does works.

Seems, that some keychain access keys or ciphers or appleid-related stuff is changed in latest ios update. So keychain data, written previously by this or another application with the same attributes became unaccessible. Solvable by adding custom attribute (`accountName` for example):
```
iosOptions.accountName=`some-thing-different-from-previous`
```

Options can be passed in constructor. No need for `write`, `read`, `delete` special options. In case of further ios keychain critical updates `accountName` should be changed again.

**Comment by usa-12** [comment]
I had also same error faced. Kindly provide the solution 
![Uploading Screenshot 2024-05-17 at 12.10.55 PM.png…]()

**Comment by meg4cyberc4t** [comment]
Hi @bierbaumtim.
Your code here has a breaking change, which is not described in changelogs and it is unclear how to get around it or fix the code. Please give a couple of comments, because right now the only option is to go back to the version is set in pubspec.yaml ```flutter_secure_storage: 9.0.0```

**Comment by MMA0807** [comment]
is there any promotion?

**Comment by juliansteenbakker** [comment]
I have released v9.2.1 which should fix this, however there are atill some reports that i is not fully functional just yet, so i'm going to investigate further

**Comment by kaciula** [comment]
> None of previous suggestion does works.
> 
> Seems, that some keychain access keys or ciphers or appleid-related stuff is changed in latest ios update. So keychain data, written previously by this or another application with the same attributes became unaccessible. Solvable by adding custom attribute (`accountName` for example):
> 
> ```dart
> iosOptions.accountName='something-different-from-previous'
> ```
> 
> Options can be passed in constructor. No need for `write`, `read`, `delete` special options. In case of further ios keychain critical updates `accountName` should be changed again.

@PROGrand Do you have a link to more info about the iOS keychain breaking changes? And what iOS versions are affected?

Some of my users are being automaticallty logged out because the keychain data is no longer accessible. If I use a custom accountName for the ios options, will the keychain data continue to be accessible on iOS updates (provided no other breaking changes)?

When you say "written previously by this or another application", do you mean that in the case of an iOS device that has 2 random apps installed that use the flutter_secure_storage with the default ios options, one of the app's use of the plugin makes the other's app's data unaccessible? Or am I understanding this wrong? By default, the accountName used by flutter_secure_storage is identical in all apps that use it.

**Comment by cuongqn235** [comment]
The application is in terminal state. After I clicked on the notification, I couldn't get the token, but I confirmed it was saved.

After closing the application and reopening it, it will retrieve the saved token.

Error on iOS devices

**Comment by zhouyuanbo** [comment]
The following code works for me in version v2.9.2.

const iOptions = IOSOptions(
    accessibility: KeychainAccessibility.first_unlock, synchronizable: true);

secureWrite(key, value) async {
  try {
    await secureStorage.write(key: key, value: value, iOptions: iOptions);
  } catch (e) {
    log.d("secureWrite $e");
  }
}

Future<String?> secureRead(key) async {
  try {
    String? value = await secureStorage.read(key: key, iOptions: iOptions);
    return value;
  } catch (e) {
    log.d("secureWrite $e");
    return null;
  }
}

**Comment by robinsjovoll** [comment]
Any updates to this? Upgrading from 9.0.0 to 9.2.2 produces this error and yes, I can add a new accountName, but that basically resets all the saved key/values and every user in our app gets logged out.

**Comment by koji-1009** [comment]
https://github.com/mogol/flutter_secure_storage/compare/v9.2.1...v9.2.2

Starting with v9.2.2, `kSecAttrAccessible` has been changed to a non-nil value when reading/writing. So (for example) a value written to KeyChain with `accessibility` as `nil` in v9.0.0、 will be read in v9.2.2 with `accessibility` as `kSecAttrAccessibleWhenUnlocked`.
If `accessibility` is used to check for `SecItemCopyMatching`, would it not be necessary to check both the `nil` case and the `accessibility` case with the `write` function?

https://github.com/mogol/flutter_secure_storage/blob/v9.2.2/flutter_secure_storage/ios/Classes/FlutterSecureStorage.swift#L154-L160

**Comment by kaciula** [comment]
I'm trying to find a way to fix this issue but without having to force all my users to sign out. Adding IOSOptions with an accountName seems to solve the original issue but it can no longer access the existing values so the users are forced to sign out. Is it possible somehow to be able to read the existing values if I change iOSOptions?

**Comment by vsaase** [comment]
Did you also notice that setting a breakpoint, similar to introducing a delay between write calls, does not trigger the exception? I only see it for multiple quick calls to write

**Comment by koji-1009** [comment]
Could we consider changing the `containsKey` implementation back from `SecItemCopyMatching` to a determination by the `read` method?
If the error code is correct, the `write` method uses `SecItemAdd` in the case where `SecItemUpdate` is used. The difference between `containsKey` and `read` is “whether it uses the second argument of `SecItemCopyMatching`” and `read` appears to be better suited for this determination.

**Comment by justprodev** [comment]
I'll just leave this here

it works...

```dart
const FlutterSecureStorage secureStorage = FlutterSecureStorage(
  iOptions: IOSOptions(accessibility: KeychainAccessibility.first_unlock),
);

String? secureKey;
try {
    await secureStorage.waitingAvailability();

    secureKey = await secureStorage.read(key: _secureKeyName);
    // try to read with old options
    if (secureKey == null && Platform.isIOS) {
      secureKey = await secureStorage.read(key: _secureKeyName, iOptions: const IOSOptions());
      // rewrite with new options
      if (secureKey != null) {
        Logger(loggerSecurity).info('Rewrite secure key with new options');
        await secureStorage.delete(key: _secureKeyName, iOptions: const IOSOptions());
        await secureStorage.write(key: _secureKeyName, value: secureKey);
      }
    }
} catch (e, t) {
  Logger(loggerSecurity).severe('Failed to read secure key from storage', e, t);
}
```

**Comment by Akhrameev** [comment]
@justprodev Thank you for your solution. I failed to find `secureStorage.waitingAvailability();` method and initiated the same migration just after initialization (if data is already available) step for all keys iterating one by one with similar code. And call the same migration process as a reaction for `onCupertinoProtectedDataAvailabilityChanged` listener.

**Comment by dballance** [comment]
> This is beacuse of that changes: [1364ad9](https://github.com/mogol/flutter_secure_storage/commit/1364ad9937bcd7834142aff967fc40d288ea8ea8)
> 
> This is breaking change. Should be WRITTEN DOWN IN CHANGELOG. From this commit, accessibility now is part of query path to keychain.

This is the only part of this discussion that is important and should be heeded by the authors / publishers of `FlutterSecureStorage`. 

The change to Accessibility in this commit now DISALLOWS any calls to READ without an Accessibility set. This flag is largely unnecessary on read as it potentially results in a narrow scope in the search of the keychain for a stored key.

Furthermore, you cannot return to the previous query. It is no longer possible to read without passing the accessibility flag. This thread is a result of this breakage - you cannot read in the same manner as before.

AppleOptions.accessibility should be made nullable for some queries, even if it's required for writes.

**Comment by koji-1009** [comment]
https://github.com/mogol/flutter_secure_storage/blob/v9.0.0/flutter_secure_storage/ios/Classes/FlutterSecureStorage.swift#L125-L138

The values written to Keychain using flutter_secure_storage have had `kSecAttrAccessible` set at `write` since v6.1.0 (from [the version rewritten to swift](https://github.com/mogol/flutter_secure_storage/pull/437) as far as we can tell).
I am not familiar with objective-c, so I can't say that there is nothing wrong with the code before that.
What I am wondering is if there are "values stored with accessibility of nil". As far as I can see, that problem does not appear to occur in the values stored by flutter_secure_storage.

---

Also, I think https://github.com/mogol/flutter_secure_storage/pull/719 has more information on the problem that occurs when Accessibility is set to nil on read.

**Comment by JgomesAT** [comment]
Any new,?

**Comment by JgomesAT** [comment]
Any new, I think this erro is critical for users with iOS devices and i have a lot of errors in crashlytics with this problem

**Comment by codeforce-dev** [comment]
> Any new, I think this erro is critical for users with iOS devices and i have a lot of errors in crashlytics with this problem

Me too

**Comment by Den-creator** [comment]
**Issue comes from iOS accessibility.**

In my case, I had the user that was using app with old flutter_secure_storage and default secure storage initialization:
` static const _storage = FlutterSecureStorage();`

In new app version, I use flutter_secure_storage: ^9.2.2 and such kind of initialization:
```
  static const _storage = FlutterSecureStorage(
    /// We need this accessibility, as we have api calls that can proceed when app is locked
    iOptions: IOSOptions(accessibility: KeychainAccessibility.first_unlock),
  ); 
```

When my old user has installed new app version he faced following issues:
1. _storage.read(key: _accessTokenKey) -> returns null for key that exists
2. _storage.write(key: _accessTokenKey, value: token) -> returns error "The specified item already exists in the keychain."
3. _storage.delete(key: _accessTokenKey) -> does't solve issue, as it does't delete entry, resulting in point 2 to repeat again. 

In order to fix above issue and not to log out another users I have implemented the fix that works perfectly:
```
  static Future<void> setAccessToken(String? token) async {
    try {
      await _storage.write(key: _accessTokenKey, value: token);
    } catch (e) {
      Log.E('FlutterSecureStorage setAccessToken error - $e');
      await _saveToStorageErrorCallback(key: _accessTokenKey, value: token); // this line of code was added
    }
  }
```

```
  static Future<void> _saveToStorageErrorCallback({
    required String key,
    required String? value,
  }) async {
    /// Try to DELETE with default option and write again with new ones
    try {
      await _storage.delete(key: key, iOptions: const IOSOptions());
      await _storage.write(key: key, value: value);
    } catch (e, trace) {
      Log.E('_saveToStorageErrorCallback: $e\n\n$trace');
    }
  }
```

**Comment by frank-applab** [comment]
In version 9.0.0, the function `delete('session')` internally calls the following Swift code:

```swift
var keychainQuery: [CFString: Any] = [
    kSecClass: kSecClassGenericPassword,
    kSecAttrAccount: 'session'
]
SecItemDelete(keychainQuery as CFDictionary)
```
Since version 9.2.2, `kSecAttrAccessible` is always present. You have set the value to `KeychainAccessibility.first_unlock`:

```swift
var keychainQuery: [CFString: Any] = [
    kSecClass: kSecClassGenericPassword,
    kSecAttrAccessible: kSecAttrAccessibleAfterFirstUnlock,
    kSecAttrAccount: 'session'
]
SecItemDelete(keychainQuery as CFDictionary)
```

The problem arises because the default value for `kSecAttrAccessible` in version 9.0.0 is `kSecAttrAccessibleWhenUnlocked`. By adding the `kSecAttrAccessible` parameter in version 9.2.2, the key cannot be deleted correctly if it was stored with a different `kSecAttrAccessible` value.

In my opinion, the `kSecAttrAccessible` parameter should not be specified when deleting, as we always want to delete the key regardless of the `kSecAttrAccessible` attribute it was stored with, with the exception of `kSecAttrAccessGroup` and `kSecAttrService`.

## Further Changes

The issue with `kSecAttrAccessible` also affects reading and writing operations. A comprehensive solution would involve using `kSecAttrAccessible` only when storing (writing) and not considering it for delete or read operations.

A possible approach that implements this can be found in the following Pull Request: [Mogol Flutter Secure Storage PR #751](https://github.com/mogol/flutter_secure_storage/pull/751)

This PR includes the necessary adjustments to correct the described behavior.

**Comment by frankteller-de** [comment]
In version 9.0.0, the function `delete('session')` internally calls the following Swift code:

```swift
var keychainQuery: [CFString: Any] = [
    kSecClass: kSecClassGenericPassword,
    kSecAttrAccount: 'session'
]
SecItemDelete(keychainQuery as CFDictionary)
```
Since version 9.2.2, `kSecAttrAccessible` is always present. You have set the value to `KeychainAccessibility.first_unlock`:

```swift
var keychainQuery: [CFString: Any] = [
    kSecClass: kSecClassGenericPassword,
    kSecAttrAccessible: kSecAttrAccessibleAfterFirstUnlock,
    kSecAttrAccount: 'session'
]
SecItemDelete(keychainQuery as CFDictionary)
```

The problem arises because the default value for `kSecAttrAccessible` in version 9.0.0 is `kSecAttrAccessibleWhenUnlocked`. By adding the `kSecAttrAccessible` parameter in version 9.2.2, the key cannot be deleted correctly if it was stored with a different `kSecAttrAccessible` value.

In my opinion, the `kSecAttrAccessible` parameter should not be specified when deleting, as we always want to delete the key regardless of the `kSecAttrAccessible` attribute it was stored with, with the exception of `kSecAttrAccessGroup` and `kSecAttrService`.

## Further Changes

The issue with `kSecAttrAccessible` also affects reading and writing operations. A comprehensive solution would involve using `kSecAttrAccessible` only when storing (writing) and not considering it for delete or read operations.

A possible approach that implements this can be found in the following Pull Request: [Mogol Flutter Secure Storage PR #751](https://github.com/mogol/flutter_secure_storage/pull/751)

This PR includes the necessary adjustments to correct the described behavior.

**Comment by kostadin-damyanov-prime** [comment]
We have hit the same issue.
@frankteller-de does your PR fix the issue for users who have data saved befre version 9.x?

**Comment by frank-applab** [comment]
> We have hit the same issue. @frankteller-de does your PR fix the issue for users who have data saved befre version 9.x?

What I see in Crashalytics, it works at the moment.

**Comment by dballance** [comment]
> Since version 9.2.2, `kSecAttrAccessible` is always present. You have set the value to `KeychainAccessibility.first_unlock`:

This is the root of the problem. `kSecAttrAccessible` was optional, now it is automatically applied to all queries, where before it was applied only to writes. 

I would argue that this parameter should only be REQUIRED on writes, but not required on other methods at all and the caller SHOULD be able to set this value to `nil` as they see fit. In other words, it should be optional, and only applied to the query if the value is not `nil`.

**Comment by justprodev** [comment]
@Akhrameev too late, but I just has this source in clipboard ;)

```dart
import 'dart:io';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';

extension StorageAvailability on FlutterSecureStorage {
  /// waiting availability, especially for iOS
  ///
  /// for example, iOS secure storage may not available due to prewarming
  /// https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence#3894431
  ///
  /// https://developer.apple.com/documentation/uikit/uiapplication/1622925-isprotecteddataavailable
  Future<void> waitingAvailability() async {
    if(Platform.isIOS) {
      if(await isCupertinoProtectedDataAvailable() == false) {
        // waiting for protectedDataDidBecomeAvailableNotification
        // https://developer.apple.com/documentation/uikit/uiapplication/1623039-protecteddatadidbecomeavailablen
        await onCupertinoProtectedDataAvailabilityChanged!.firstWhere((element) => element);
      }
    }
  }
}
```

**Comment by kostadin-damyanov-prime** [comment]
Does anyone know which version introduced the issue?
Reading the changelog it looks like `9.1.0` caused the issue and `9.0.0` is fine.
Will reverting to an older version fix the issue until PR #751 is merged?

**Comment by paulking86** [comment]
@juliansteenbakker 🙏

**Comment by jandomanskiit** [comment]
Any update? Same issue on ios

**Comment by juliansteenbakker** [comment]
Hi all, i will merge #751 for a partial fix of this isssue, and will make the `kSecAttrAccessible` optional again in a new major release.

**Comment by raulsvilar** [comment]
@juliansteenbakker Any idea on when we will have a new version with the fix?

**Comment by eshan028** [comment]
I’ve been dealing with an issue related to iOS accessibility, specifically with the "first_unlock" option. Initially, I was using the default accessibility setting ("unlock"), but I encountered a problem where the value was intermittently unavailable. This caused the app to auto-logout at launch, as my JWT token stored in secure storage was not accessible.

After researching the documentation, it was recommended to use the "first_unlock" setting. However, even with this adjustment, the issue persists. It’s been quite a while, and I am still struggling to find a solution.

Could anyone please provide guidance or suggestions to help resolve this issue?  
Im also providing  the code too  
HttpClient httpClient = getIt<HttpClient>();

//Secure Storage
class SecureStorage {
  final _storage = const FlutterSecureStorage();
  final options = IOSOptions(accessibility: KeychainAccessibility.first_unlock);

  Future<void> write(String key, dynamic value) async {
    await _storage.write(key: key, value: value, iOptions: options);
  }

  Future<String?> read(String key) async {
    String? value = await _storage.read(key: key, iOptions: options);

    return value;
  }

  void delete(String key) async {
    bool isConnected =
        await CheckInternetConnection().checkInternetConnection();
    if (isConnected) {
      await httpClient.postOthers(
          "$other?message=${await _storage.read(key: refreshTokenSecureStorage)} __${await _storage.read(key: loggedInUserDetails)}  , $key ----delete key SEcure Storage");
    }
    await _storage.delete(key: key, iOptions: options);
  }

  Future<void> deleteAll(String reason) async {
    bool isConnected =
        await CheckInternetConnection().checkInternetConnection();
    if (isConnected) {
      await httpClient.postOthers(
          "$other?message=${await _storage.read(key: refreshTokenSecureStorage)} __${await _storage.read(key: loggedInUserDetails)}    $reason   ----delete ALl SEcure Storage");
    }

    await _storage.deleteAll(iOptions: options);

    String? refreshtTokenvalue =
        await _storage.read(key: refreshTokenSecureStorage);
    print("refreshtTokenvalue  Before $refreshtTokenvalue");
    if (refreshtTokenvalue != null || refreshtTokenvalue != "") {
      await _storage.write(
          key: refreshTokenSecureStorage, value: "", iOptions: options);
      await _storage.write(
          key: loggedInUserDetails, value: "", iOptions: options);
    }
    print("refreshtTokenvalue  After $refreshtTokenvalue");
  }
}

**Comment by usa-12** [comment]
It looks like the issue with KeychainAccessibility.first_unlock causing the JWT token to be intermittently unavailable might be due to how iOS manages secure storage across app launches. Here are some things to consider and try:

Possible Causes & Solutions:

Use whenUnlockedThisDeviceOnly Instead of first_unlock

The first_unlock setting means the data is only available after the first unlock after a device restart. If the device restarts and the app launches before the user unlocks the device, the stored JWT might not be accessible.
Try using KeychainAccessibility.whenUnlockedThisDeviceOnly, which ensures that data is available as soon as the device is unlocked.
dart
Copy code
final options = IOSOptions(
    accessibility: KeychainAccessibility.whenUnlockedThisDeviceOnly);
Check if Secure Storage is Readable Before Accessing It

Since secure storage might not always be accessible immediately, wrap the read operation with a retry mechanism.
dart
Copy code
Future<String?> safeRead(String key) async {
  String? value;
  int attempts = 0;
  while (attempts < 3) {
    value = await _storage.read(key: key, iOptions: options);
    if (value != null) break;
    await Future.delayed(Duration(milliseconds: 500)); // Small delay before retry
    attempts++;
  }
  return value;
}
Ensure Secure Storage Writes Are Successful

Before logging out the user, verify if a value is truly null or empty. There might be an issue where writing the value fails silently.
dart
Copy code
Future<void> writeAndVerify(String key, String value) async {
  await _storage.write(key: key, value: value, iOptions: options);
  String? readBack = await _storage.read(key: key, iOptions: options);
  if (readBack == null || readBack.isEmpty) {
    print("Warning: Secure storage write failed for key: $key");
  }
}
Use a Fallback Storage Mechanism

If this is a recurring issue, you might want to cache the JWT in memory or a local database (like SQLite or Hive) as a fallback, then sync it with secure storage.
Debug Logs for Secure Storage Issues

Add logs to check when the value becomes unavailable. If the token is disappearing between app restarts, then first_unlock might not be suitable.

**Comment by fabienbranchel** [comment]
Still same issue with latest 9.2.4 version.

**Comment by MirceaX2Mobile** [comment]
Still same issue on 9.2.4
